### ISSUE TITLE
tried to implement tests but had difficulties

### ISSUE THREAD

**Issue by jfgsilva** [tsivinsky/sshx#2]
Hi, 

I saw your post on reddit some time ago, and really enjoyed what sshx accomplishes. 
I tried to contribute by trying to implement tests on the different features, but I go blocked because I can't find a way to feed input (io.Reader, io.Writer ) to Prompter which only takes ghPrompter.FileReader and ghPrompter.FileWriter as arguments.

Would you have any suggestions?

**Comment by tsivinsky** [comment]
Hi,

based on `FileReader` interface it takes `io.Reader` and has method `Fd() uintptr`

```go
type FileReader interface {
	io.Reader
	Fd() uintptr
}
```

I think you can create mock struct with `Fd` method which will return zero value for `uintptr`. actually I don't know if it's any good as I'm not that good with Go :)

**Comment by jfgsilva** [comment]
It seems that it would be preferable to assume prompter is tested. It's easier to refactor sshx and mock prompter as a whole. I'll refactor and create PR if you're ok with it

**Comment by tsivinsky** [comment]
yeah, sure. go ahead
